# Generated by Django 4.0.1 on 2022-01-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='모코코', max_length=20)),
                ('content', models.CharField(default='', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guestbook',
            },
        ),
    ]
